# Generated by Django 4.2 on 2023-07-28 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0002_alter_contragent_options_alter_nomenclature_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contragent',
            options={'verbose_name': 'Контрагент', 'verbose_name_plural': 'Контрагенты'},
        ),
        migrations.AlterModelOptions(
            name='nomenclature',
            options={'verbose_name': 'Номенклатура', 'verbose_name_plural': 'Номенклатура'},
        ),
        migrations.AlterModelOptions(
            name='vehicles',
            options={'verbose_name': 'Автомобиль', 'verbose_name_plural': 'Автомобили'},
        ),
    ]
