# Generated by Django 3.2 on 2023-07-27 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_document_total_per_document'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentitem',
            options={'ordering': ['-document', 'position'], 'verbose_name': 'Товар в документе', 'verbose_name_plural': 'Товары в документах'},
        ),
    ]
