# Generated by Django 4.2 on 2023-07-28 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_documentitem_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='contragent',
        ),
        migrations.RemoveField(
            model_name='document',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='document',
            name='transport',
        ),
        migrations.RemoveField(
            model_name='documentitem',
            name='document',
        ),
        migrations.RemoveField(
            model_name='documentitem',
            name='nomenclature',
        ),
        migrations.RemoveField(
            model_name='nomenclature',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='vehicles',
            name='deleted_by',
        ),
        migrations.DeleteModel(
            name='Contragent',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='DocumentItem',
        ),
        migrations.DeleteModel(
            name='Nomenclature',
        ),
        migrations.DeleteModel(
            name='Vehicles',
        ),
    ]
