# Generated by Django 4.2 on 2023-07-28 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('type', models.CharField(choices=[('0', 'Приход'), ('1', 'Расход'), ('2', 'Перемещение'), ('3', 'Возврат')], default='1', max_length=1)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('is_factura', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now=True)),
                ('total_per_document', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('contragent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalogs.contragent')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('transport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='catalogs.vehicles')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='DocumentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='Position')),
                ('taratype', models.CharField(choices=[('0', 'Светлое'), ('1', 'Темное'), ('2', 'Белое')], default='0', max_length=1)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Price')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Quantity')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='documents.document')),
                ('nomenclature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogs.nomenclature')),
            ],
            options={
                'verbose_name': 'Товар в документе',
                'verbose_name_plural': 'Товары в документах',
                'ordering': ['-document', 'position'],
            },
        ),
    ]
