# Generated by Django 4.2 on 2023-07-28 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.AlterModelOptions(
            name='documentitem',
            options={'verbose_name': 'Товар в документе', 'verbose_name_plural': 'Товары в документах'},
        ),
    ]
