# Generated by Django 4.2 on 2023-07-28 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_options_alter_documentitem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-date'], 'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.AlterModelOptions(
            name='documentitem',
            options={'ordering': ['-document', 'position'], 'verbose_name': 'Товар в документе', 'verbose_name_plural': 'Товары в документах'},
        ),
    ]
