# Generated by Django 4.2 on 2023-07-28 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_document_options_alter_documentitem_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='code',
            new_name='number',
        ),
    ]
