# Generated by Django 4.2 on 2023-07-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_rename_code_document_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
