# Generated by Django 4.2 on 2023-07-28 11:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_document_created_alter_document_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
